#!/usr/bin/env bash

read -r USER_ID < <(id -u)
read -r SESSION_ID < <(loginctl show-user "${USER}" -p Display --value)
[[ -n "${SESSION_ID}" ]] && export XDG_SESSION_ID="${SESSION_ID}"
unset SESSION_ID

[ -f ~/.config/dotf/setup-env ] && source ~/.config/dotf/setup-env

systemd-run --user --no-block \
  --unit=hyprwm-socket-wait \
  --property=Type=oneshot \
  --property=Wants=graphical-session-pre.target \
  --property=After=graphical-session-pre.target \
  --property=Before=graphical-session.target \
  --ignore-failure \
  --collect \
  bash ~/.config/dotf/socket-wait

exec systemd-run --user --pty --wait \
  --unit=hyprwm \
  --slice=session-graphical.slice \
  --property=BindsTo=graphical-session.target \
  --property=Wants=graphical-session-pre.target \
  --property=After=graphical-session-pre.target \
  --property=Before=graphical-session.target \
  --ignore-failure \
  --collect \
  start-hyprland

