#!/usr/bin/bash
# zoom in-out: zoom [-+]<factor>?
# 🔗 https://github.com/klapptnot/dotf

m="${1:0:1}"
f="${1:1}"
[[ "${m}" == '+' || "${m}" == '-' ]] \
  && read -r zf < <(hyprctl getoption cursor:zoom_factor | awk -v f="${f:-0.5}" "/^float.*/ {print \$2 ${m} f}")
[[ -z "${zf@A}" ]] && zf="${1}"
[[ -z "${zf}" ]] && zf='1'

hyprctl keyword cursor:zoom_factor "${zf}"

