#!/usr/bin/env bash

# reset first, to only keep running ones (if nor running, they disappear)
# because they are also transient, started with `systemd-run`
systemctl --user reset-failed 'hypr-autostart-*' 2> /dev/null

if [ "${1}" == 'stop' ]; then
  systemctl --quiet --user is-active --all 'hypr-autostart-*' \
    && systemctl --user stop 'hypr-autostart-*'
  exit "${?}"
fi

# do not start any unit if some units are running, print them
systemctl --quiet --user is-active --all 'hypr-autostart-*' && {
  systemctl --user list-units 'hypr-autostart-*' --no-legend | awk '{print $1 " " $4 " " $6}'
  exit 0
}

gsettings set org.gnome.desktop.interface gtk-theme "catppuccin-mocha-mauve-standard+default"
gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
gsettings set org.gnome.desktop.interface cursor-theme "hatsune-miku-cursor"
gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"

function run_as_unit {
  {
    read -r rsm < <(rsum -l 8 -c 'a-z0-9')
    local unit_name="hypr-autostart-${rsm}"

    local -a systemd_args=(
      --user
      --property=BindsTo=hyprwm.service
      --property=After=hyprwm.service
      --slice=background-graphical.slice
      --unit="${unit_name}"
    )

    if [[ "${1}" == "@gnome" ]]; then
      shift
      systemd_args+=(
        --setenv=XDG_CURRENT_DESKTOP=GNOME
        --setenv=XDG_SESSION_DESKTOP=gnome
      )
    fi

    systemd-run "${systemd_args[@]}" -- "${@}" &> /dev/null
  } &
}

run_as_unit fcitx5
run_as_unit nm-applet
run_as_unit lbagtk

# as gnome for right-click wallpaper
run_as_unit @gnome thunar --daemon

if [ -x /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 ]; then
  run_as_unit /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
elif [ -f /usr/lib/polkit-kde-authentication-agent-1 ]; then
  run_as_unit /usr/lib/polkit-kde-authentication-agent-1
fi

run_as_unit bash ~/.config/hypr/bin/medialock backend
run_as_unit bash ~/.config/hypr/bin/adopt-gnome-bg
